server:
  port: 8080

spring:
  main:
    web-application-type: servlet
  application:
    name: transaction-service

serviex:
  base-url: http://localhost:9090
  transactions-path: /getTrx

jwt:
  secret: local-dev-secret-change-me-1234567890

error:
  mapping:
    code: SERVIEX_CONFLICT
    error: 500
